### ISSUE TITLE
JSON type inference

### ISSUE THREAD

**Issue by karlhorky** [ts-safeql/safeql#190]
Supersedes https://github.com/ts-safeql/safeql/issues/102
Supersedes https://github.com/ts-safeql/safeql/issues/179

**Is your feature request related to a problem? Please describe.**

JSON functions such as `json_agg` and `json_build_object` and JSON literals return `any` types instead of the type of the data.

There are [ways of getting around this with `connections.overrides.types.json`](https://github.com/ts-safeql/safeql/issues/102#issuecomment-1318322571), but this is limiting:

```js
{
  "connections": {
    // ...
    "overrides": {
      "types": {
        "json": "JsonAgg"
      }
    }
  }
}
```

For example, once we have configured this, we can add the `JsonAgg` type as in the example below.

However, there are problems with this:

1. If we want to have multiple `json_agg` queries in the same file, it fails, because it uses the name `JsonAgg`
2. The types are not checked

```ts
type Food = { id: number; name: string; };

type JsonAgg = Food[];

type AnimalWithFoodsInJsonAgg = {
  animalId: number;
  animalFoods: JsonAgg | null;
};

function getAnimalWithFoodsById(async (id: number) {
  const [animal] = await sql<AnimalWithFoodsInJsonAgg[]>`
    SELECT
      animals.id AS animal_id, (
        SELECT json_agg (foods.*)
        FROM
          animal_foods
          INNER JOIN foods ON animal_foods.food_id = foods.id
        WHERE
          animal_foods.animal_id = animals.id
      ) AS animal_foods
    FROM animals
    WHERE animals.id = ${id}
    GROUP BY animals.id;
  `;
  return animal;
}
```

**Describe the solution you'd like**

One potential solution is to [use PostgreSQL `COMMENT`s like Kanel by @kristiandupont does](https://github.com/ts-safeql/safeql/issues/102#issuecomment-1833196632)

Support list:

- [ ] `json_build_object`
- [ ] `json_agg`
- [ ] literal JSON

**Describe alternatives you've considered**

Running subqueries / parsing JSON in the query:

- https://github.com/ts-safeql/safeql/issues/102#issuecomment-1837529885

**Additional context**

--

**Comment by Newbie012** [comment]
Just release [@ts-safeql/eslint-plugin@3.0.0-next.0](https://www.npmjs.com/package/@ts-safeql/eslint-plugin/v/3.0.0-next.0), now with type-checking for json/b expressions 🚀🚀

But please keep in mind that it doesn't cover all cases (such as functions/subselects inside jsonb_agg), but it works fine for simpler scenarios. More improvements are on the way, but I wanted to get this out now.

All feedback is welcome and appreciated 🙏

**Comment by karlhorky** [comment]
@Newbie012 thanks for this! I checked this out just now and wrote some notes:

## Works as expected

### `json_build_object` 1

```ts
await sql<{ json_build_object: { id: number } }[]>`
  SELECT
    json_build_object('id', animals.id)
  FROM
    animals
`;
```

Like [this test](https://github.com/ts-safeql/safeql/blob/1d8406dee591193a22abdcd12cade99d6c3a00bd/packages/eslint-plugin/src/rules/check-sql.test.ts#L1319-L1324)

### `json_agg() AS` field 

```ts
await sql<
  {
    colname: {
      id: number;
      name: string;
      type: string;
    }[];
  }[]
>`
  SELECT
    json_agg(foods) AS colname
  FROM
    foods
`;
```

Like [this test](https://github.com/ts-safeql/safeql/blob/1d8406dee591193a22abdcd12cade99d6c3a00bd/packages/eslint-plugin/src/rules/check-sql.test.ts#L1365-L1372)

## Not working yet as expected

### `json_agg() AS` field with nullable fields

```ts
await sql<
  {
    colname: {
      id: number;
      firstName: string;
      type: string;
      accessory: string | null;
      birthDate: Date;
    }[];
  }[]
>`
  SELECT
    json_agg(animals) AS colname
  FROM
    animals
`;
```

Like [this test](https://github.com/ts-safeql/safeql/blob/1d8406dee591193a22abdcd12cade99d6c3a00bd/packages/eslint-plugin/src/rules/check-sql.test.ts#L1365-L1372)

**Error**

```
Query has incorrect type annotation.
	Expected: { colname: { id: number; firstName: string; type: string; accessory: string | null; birthDate: Date }[] }[]
	Actual: { colname: { id: number; firstName: string; type: string; accessory: string; birthDate: Date }[] }[]
```

The `animals.accessory` field should be nullable:

```sql
CREATE TABLE animals (
  id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  first_name varchar(30) NOT NULL,
  type varchar(30) NOT NULL,
  accessory varchar(30),
  birth_date date NOT NULL
);
```

### `json_agg AS` field inside subquery

```ts
await sql<
  {
    colname: {
      id: number;
      name: string;
      type: string;
    }[];
  }[]
>`
  SELECT
    (
      SELECT
        json_agg(foods)
      FROM
        foods
    ) AS colname
  FROM
    foods
`;
```

@Newbie012 mentioned subqueries in [his comment](https://github.com/ts-safeql/safeql/issues/190#issuecomment-1854912960) above, so it may be that this is also not yet supported.

**Error**

```
Query has incorrect type annotation.
	Expected: { colname: { id: number; name: string; type: string }[] }[]
	Actual: { colname: JsonAgg | null }[]
```

### `json_agg() AS` field with `FROM` clause subquery derived table

@Newbie012 mentioned subqueries in [his comment](https://github.com/ts-safeql/safeql/issues/190#issuecomment-1854912960) above, so it may be that this is also not yet supported.

```ts
await sql<
  {
    colname: {
      id: number;
      name: string;
      type: string;
    }[];
  }[]
>`
  SELECT
    json_agg(foods) AS colname
  FROM
    (
      SELECT
        *
      FROM
        foods
    ) AS foods
`;
```

**Error**

```
Query has incorrect type annotation.
	Expected: { colname: { id: number; name: string; type: string }[] }[]
	Actual: { colname: JsonAgg | null }[]
```

**Comment by karlhorky** [comment]
Nice, I can confirm this is working in one of our projects, upgrade PR here:

- https://github.com/upleveled/next-js-example-fall-2023-atvie/pull/16

However, in [the CI run](https://github.com/upleveled/next-js-example-fall-2023-atvie/actions/runs/7247618029/job/19741909572?pr=16), it appears that running ESLint via the command line causes resolution problems with the `@ts-safeql/shared` package (we're using `pnpm`):

```bash
pnpm eslint . --max-warnings 0
(node:3063) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

Oops! Something went wrong! :(

ESLint: 8.55.0

Error: Cannot find module '/home/runner/work/next-js-example-fall-2023-atvie/next-js-example-fall-2023-atvie/node_modules/.pnpm/@ts-safeql+eslint-plugin@3.0.0-next.1_eslint@8.55.0_libpg-query@15.0.2_typescript@5.2.2/node_modules/@ts-safeql/shared/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:444:19)
    at Module._findPath (node:internal/modules/cjs/loader:715:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1130:27)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/home/runner/work/next-js-example-fall-2023-atvie/next-js-example-fall-2023-atvie/node_modules/.pnpm/@ts-safeql+eslint-plugin@3.0.0-next.1_eslint@8.55.0_libpg-query@15.0.2_typescript@5.2.2/node_modules/@ts-safeql/eslint-plugin/lib/rules/check-sql.rule.js:7:18)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
```

Is there something I did wrong that I should fix here?

Our [ESLint config](https://github.com/upleveled/eslint-config-upleveled/blob/32b814aa80a04863fef253333f4ab8592a48a08a/index.js#L947-L970) specifies SafeQL like this, has been working since we installed SafeQL back close to the first available version:

```ts
  firstConfig.plugins['@ts-safeql'] = await import('@ts-safeql/eslint-plugin');

  firstConfig.rules['@ts-safeql/check-sql'] = [
    'error',
    {
      connections: [
        {
          databaseUrl: `postgres://${process.env.PGUSERNAME}:${process.env.PGPASSWORD}@${process.env.PGHOST}:5432/${process.env.PGDATABASE}`,
          targets: [
            {
              tag: 'sql',
              fieldTransform: 'camel',
              transform: '{type}[]',
            },
          ],
          overrides: {
            types: {
              json: 'JsonAgg',
            },
          },
        },
      ],
    },
  ];
```

**Comment by karlhorky** [comment]
Ah looks like [`@ts-safeql/shared@3.0.0-next.1`](https://www.npmjs.com/package/@ts-safeql/shared/v/3.0.0-next.1?activeTab=code) is missing some file(s):

![Screenshot 2023-12-18 at 13 05 29](https://github.com/ts-safeql/safeql/assets/1935696/e3f9cc73-3911-4c99-8bf1-189124bf8d8a)

**Comment by Newbie012** [comment]
My bad. I'm building the `.next` versions locally on my machine, so I made a human error by not building all of the monorepo packages before publishing the version. Should be okay in `3.0.0-next.2` (hopefully).

I should probably use [tsup](https://tsup.egoist.dev/) for bundling, but that's for another day.

**Comment by karlhorky** [comment]
Ok, with `@ts-safeql/eslint-plugin@3.0.0-next.2` no more dependency errors anymore, but now I have a type mismatch again:

```
Query has incorrect type annotation.
	Expected: { animalId: number; animalFirstName: string; animalType: string; animalAccessory: null | string; animalFoods: null | Array }[]
	Actual: { animalId: number; animalFirstName: string; animalType: string; animalAccessory: string | null; animalFoods: JsonAgg | null }[]
```

Query + type:

```ts
type AnimalWithFoods = {
  animalId: number;
  animalFirstName: string;
  animalType: string;
  animalAccessory: string | null;
  animalFoods: Food[] | null;
};

  const [animal] = await sql<AnimalWithFoods[]>`
    SELECT
      animals.id AS animal_id,
      animals.first_name AS animal_first_name,
      animals.type AS animal_type,
      animals.accessory AS animal_accessory,
      (
        SELECT
          json_agg(foods.*)
        FROM
          animal_foods
          INNER JOIN foods ON animal_foods.food_id = foods.id
        WHERE
          animal_foods.animal_id = animals.id
      ) AS animal_foods
    FROM
      animals
    WHERE
      animals.id = ${id}
    GROUP BY
      animals.first_name,
      animals.type,
      animals.accessory,
      animals.id;
  `;
```

Maybe the subquery in the `SELECT` is one of the last things that isn't working yet?

I thought I saw it working on my machine when I first installed `@ts-safeql/eslint-plugin@3.0.0-next.1`, but maybe I tricked myself.

**Comment by Newbie012** [comment]
Yeah, I missed the failing tests. I'll create a new release soon.

On a different note, it turns out that jsonb_agg is nullable and can potentially contain null values:

```sql
-- If no data rows are selected, jsonb_agg is nullable
SELECT jsonb_agg(a)
FROM (SELECT NULL::integer AS a WHERE false) sub;

-- If some of the data rows are null, jsonb_agg can contain null values
SELECT jsonb_agg(a)
FROM (VALUES (1), (2), (NULL)) AS vals(a);
```

While the safest approach is to generate `{ jsonb_agg: (T | null)[] | null }`, in most cases, it's in fact `T[]`, but I treat every type as nullable until proven otherwise. In a nutshell, I may have to do additional nullability checks before 3.0.0.

**Comment by Newbie012** [comment]
Just released `3.0.0-next.3` which many small issues such as mistakenly inferring `T[]` as `Array`.

**Comment by karlhorky** [comment]
Right ok, now with `@ts-safeql/eslint-plugin@3.0.0-next.3` we're back to the `Food[]` vs `JsonAgg` error message:

```
Query has incorrect type annotation.
	Expected: { animalId: number; animalFirstName: string; animalType: string; animalAccessory: null | string; animalFoods: null | Food[] }[]
	Actual: { animalId: number; animalFirstName: string; animalType: string; animalAccessory: string | null; animalFoods: JsonAgg | null }[]
```

**Comment by karlhorky** [comment]
@Newbie012 in the query from the other repo, one thing I considered was moving to inner joins instead of using the subquery:

```
type Food = {
  id: number;
  name: string;
  type: string;
};

type AnimalWithFoods = {
  animalId: number;
  animalFirstName: string;
  animalType: string;
  animalAccessory: string | null;
  animalFoods: Food[] | null;
};

  const [animal] = await sql<AnimalWithFoods[]>`
    SELECT
      animals.id AS animal_id,
      animals.first_name AS animal_first_name,
      animals.type AS animal_type,
      animals.accessory AS animal_accessory,
      json_agg(foods.*) AS animal_foods
    FROM
      animals
      INNER JOIN animal_foods ON animals.id = animal_foods.animal_id
      INNER JOIN foods ON foods.id = animal_foods.food_id
    WHERE
      animals.id = ${id}
    GROUP BY
      animals.first_name,
      animals.type,
      animals.accessory,
      animals.id
  `;
```

This seems like it should work, but SafeQL has problems resolving the `Food` type alias:

```
Query has incorrect type annotation.
	Expected: { animalId: number; animalFirstName: string; animalType: string; animalAccessory: null | string; animalFoods: null | Food[] }[]
	Actual: { animalId: number; animalFirstName: string; animalType: string; animalAccessory: string | null; animal_foods: { id: number; name: string; type: string }[] }[]
```

Commit here:

- [upleveled/next-js-example-fall-2023-atvie@`46e124f` (#16)](https://github.com/upleveled/next-js-example-fall-2023-atvie/pull/16/commits/46e124fea514f8b5b2afffebcefff45dcd08d6c2)

**Comment by Newbie012** [comment]
It took a while but I think it's finally ready:

```
npm i -D @ts-safeql/eslint-plugin@3.0.0.next-4
```

Up until now, SafeQL heavily relied on PostgresSQL's RowDescription message which returned the sources of the queried columns. While in most cases it was sufficient to infer the query returned type, it wasn't as precise as we wanted when dealing with complex/nested types (such as `json` and `jsonb`).

In version `3.0.0.next.4` I rewrote from scratch the way SafeQL infers the query types by introducing a new "ASTDescription" which aims to replace PostgresSQL's RowDescription as the primary "descriptor" by trying to figure out the source and the type of each target result (e.g., a returned column). If it fails to retrieve the type for any reason, it will fall back to PostgresSQL's RowDescription (the current implementation). As of writing this comment, all of the current tests (of `SELECT` statements) passes with the new `ASTDescription`.

As a result, SafeQL got more stricter and precise, and at the same time more flexible for future plans.

Any feedback would be very much appreciated.

**Comment by karlhorky** [comment]
Upgraded to `@ts-safeql/eslint-plugin@3.0.0-next.4` and there appear to be improvements, nice!

No longer is the following query using `JsonAgg`:

```ts
type Food = {
  id: number;
  name: string;
  type: string;
};

type AnimalWithFoods = {
  animalId: number;
  animalFirstName: string;
  animalType: string;
  animalAccessory: string | null;
  animalFoods: Food[] | null;
};

const [animal] = await sql<AnimalWithFoods[]>`
  SELECT
    animals.id AS animal_id,
    animals.first_name AS animal_first_name,
    animals.type AS animal_type,
    animals.accessory AS animal_accessory,
    coalesce(
      json_agg(foods.*) FILTER (WHERE foods.id IS NOT NULL),
      '[]'
    ) AS animal_foods
  FROM
    animals
    LEFT JOIN animal_foods ON animals.id = animal_foods.animal_id
    LEFT JOIN foods ON foods.id = animal_foods.food_id
  WHERE
    animals.id = ${id}
  GROUP BY
    animals.first_name,
    animals.type,
    animals.accessory,
    animals.id
`;
```

However, there is an error remaining here, it seems that there are some extra `| null`s being added:

```
Query has incorrect type annotation.
	Expected: { animalId: number; animalFirstName: string; animalType: string; animalAccessory: null | string; animalFoods: null | { id: number; name: string; type: string }[] }[]
	  Actual: { animalId: number; animalFirstName: string; animalType: string; animalAccessory: string | null; animalFoods: { id: number | null; name: string | null; type: string | null }[] }[]

eslint [@ts-safeql/check-sql](https://github.com/ts-safeql/safeql)
```

As far as I can tell, `animalFoods[number].id`, `animalFoods[number].name` and `animalFoods[number].type` should never be `null`:

```sql
CREATE TABLE foods (
  id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name varchar(30) NOT NULL,
  type varchar(30) NOT NULL
);
```

**Comment by Newbie012** [comment]
Good catch! The part responsible for the non-nullability check doesn't consider the `FILTER` keyword, so it assumes that everything in the column can be nullable because it comes from a `LEFT JOIN` relation.

Now that I have full control over the type inference, I think adding that check would be trivial as well.

**Comment by karlhorky** [comment]
> The part responsible for the non-nullability check doesn't consider the `FILTER` keyword, so it assumes that everything in the column can be nullable because it comes from a `LEFT JOIN` relation.

Even without the `FILTER`, the returned value won't be null fields/properties (I think). I receive the following when `foods` doesn't return any results:

```
[null]
```

**Comment by Newbie012** [comment]
@karlhorky when I think about it, this is a bit more complex than I initially thought. Right now, SafeQL iterates over each column and decides whether it should be nullable (or not). Instead, SafeQL should look at a group of columns, which requires fundamental changes in the way SafeQL checks for nullability (which was introduced in 2.0.0). While I'm all in for it, I think I should release 3.0.0 as is for now.

Thoughts?

**Comment by Newbie012** [comment]
fixed in 3.0.0

**Comment by karlhorky** [comment]
@Newbie012 Thanks for `@ts-safeql/eslint-plugin@3` 🙌 Really excited to have a new release here!

However, maybe we should reopen this one - it seems like `json_agg()` with a `LEFT JOIN` (mentioned in [my comment above](https://github.com/ts-safeql/safeql/issues/190#issuecomment-1883464231)) isn't quite there yet:

> So if I'm understanding correctly and this should be taken into account by SafeQL, then I guess `json_agg()` with a `LEFT JOIN` should return:
> 
> ```
> animalFoods: (null | { id: number; name: string; type: string })[]
> ```
> 
> Or, more precisely:
> 
> ```
> animalFoods: { id: number; name: string; type: string }[] | [null]
> ```

With the query below, I get this error still:

```
Query has incorrect type annotation.
	Expected: { animalFoods: { id: number; name: string; type: string }[] }[]
	  Actual: { animalFoods: { id: number | null; name: string | null; type: string | null }[] }[]
```

```ts
type Food = {
  id: number;
  name: string;
  type: string;
};

type AnimalWithFoods = {
  animalFoods: Food[];
};

const [animal] = await sql<AnimalWithFoods[]>`
  SELECT
    coalesce(
      json_agg(foods.*) FILTER (WHERE foods.id IS NOT NULL),
      '[]'
    ) AS animal_foods
  FROM
    animals
    LEFT JOIN animal_foods ON animals.id = animal_foods.animal_id
    LEFT JOIN foods ON foods.id = animal_foods.food_id
  WHERE
    animals.id = ${id}
  GROUP BY
    animals.first_name,
    animals.type,
    animals.accessory,
    animals.id
`;
```

---

I created a DB Fiddle to demonstrate the issue:

https://www.db-fiddle.com/f/3XYpPxfzaoZ3domAJD8MFx/0

![Screenshot 2024-04-25 at 18 07 40](https://github.com/ts-safeql/safeql/assets/1935696/f1d251b1-42cf-4982-924a-5f7835938293)

**Comment by Newbie012** [comment]
@karlhorky I understand that. Although, treating a group of columns as nullable rather than treating each column individually can be very complex and should be discussed further in a [separate discussion](https://github.com/ts-safeql/safeql/discussions/210).

I should probably add support for type discrimination using the `FILTER` syntax as well, but it's unrelated to this issue.

**Comment by karlhorky** [comment]
Ok thanks for opening the discussion, I'll watch and discuss over there.

> I should probably add support for type discrimination using the `FILTER` syntax as well, but it's unrelated to this issue.

Ok, opened this feature request here:

- https://github.com/ts-safeql/safeql/issues/211
